### ISSUE TITLE
Spurious `appstream-missing-screenshots` errors

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub-infra/flatpak-builder-lint#250] opened 2024-01-05 02:34 UTC
I first encountered this issue 2 days ago.

[This](https://github.com/flathub/org.octave.Octave/pull/331) Octave PR failed with this error even though it only updated a dependency and the sha of the octave archive containing the metainfo file stayed the same:

```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions repo repo
 in dir /srv/buildbot/worker/build-x86_64/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions repo repo'
 using PTY: False
{
    "errors": [
        "appstream-missing-screenshots"
    ],
    "warnings": [
        "finish-args-contains-both-x11-and-wayland"
    ]
}
program finished with exit code 1
elapsedTime=53.206962
```

Then I commented "bot, build" and the build succeeded.

But after the merge, the build of the master branch failed with the same error:
https://github.com/flathub/org.octave.Octave/commit/445f656373489a3c100b85bc8f3f6fef52297cc5

**Comment by bbhtt** [comment] 2024-01-05 02:41
The screenshot download failed there due to a connectivity issue:

```
org.octave.Octave.desktop:         Failed to download https://www.gnu.org/software/octave/img/screenshot.png: Downloading https://www.gnu.org/software/octave/img/screenshot.png failed: Failed to connect to octave.org port 443 after 421 ms: Couldn't connect to server
```

https://buildbot.flathub.org/#/builders/6/builds/91256

**Comment by Alexander-Wilms** [comment] 2024-01-05 02:51
And in that case the screenshot tag gets removed from the metainfo file that's exported using `appstream-util mirror-screenshots`?

That'd be unexpected, shouldn't the build step already fail instead?

**Comment by hfiguiere** [comment] 2024-01-05 02:56
It used to fail for that, but tooling has been changed.

**Comment by bbhtt** [comment] 2024-01-05 03:43
Yes probably, when appstream compose mirror fails it probably generates some Null or invalid value in the appstream app info data.

Not much to be done other that you have to restart the build.

**Comment by bbhtt** [comment] 2024-01-05 15:24
Let's close this. There's nothing to do here from the linter's side.

You can easily reproduce this by disabling internet and running `flatpak run org.flatpak.Builder --force-clean --sandbox --disable-download --mirror-screenshots-url=https://dl.flathub.org/repo/screenshots --repo=repo builddir <manifest>`, then the resultant catalogue in `builddir/share/app-info/xmls/$FLATPAK_ID.xml.gz` doesn't have any screenshot tag.

**Closed by bbhtt** 2024-01-05 15:24 UTC
